version: "3.8"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/nas/Config/mqtt:/mosquitto
    ports:
      - 1883:1883
    networks:
      - apps
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
networks:
  apps:
    external: true
