version: "3.8"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8100:8080
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - apps
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
networks:
  apps:
    external: true
